[package]
name = "karak-rs"
license = { workspace = true }
description = "Karak Rust SDK"
version = "0.2.0"
authors = { workspace = true }
repository = { workspace = true }
edition = { workspace = true }

[dependencies]
karak-contracts = { path = "../contracts" }
karak-kms = { path = "../kms" }
