on:
  pull_request:
  push:
    branches:
      - main

name: Continuous Integration

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@v2
      - name: Clippy
        run:
          cargo clippy --workspace --exclude karak-cli --all-targets --all-features -- -D warnings && \
          cargo clippy --package karak-cli --all-targets --features default,testnet -- -D warnings
      - name: Rustfmt
        run: cargo fmt --all --check
      - name: Check
        run:
          cargo check --workspace --exclude karak-cli --all-targets --all-features && \
          cargo check --package karak-cli --all-targets --features default,testnet

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Anvil
        uses: foundry-rs/foundry-toolchain@v1
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
      - name: Test
        run: cargo test --workspace --all-targets --all-features

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: cargo doc
        run:
          cargo doc --workspace --exclude karak-cli --all-features --no-deps && \
          cargo doc --package karak-cli --features default,testnet --no-deps
      - name: test doc
        run:
          cargo test --doc --workspace --exclude karak-cli --all-features && \
          cargo test --doc --package karak-cli --features default,testnet
